### ISSUE TITLE
Sources migrated into fty-common lack git history

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-common#18]
Instead of doing a bit of git magic to introduce sources along with their commit history into fty-common repository (so we can later inspect who did what - and why, thanks to commit messages, regardless of which repo hosted the code at that time) a snapshot of source files were just copied into fty-common making it as if an initial commit happened a few days ago. Original files are removed from fty-rest in the meanwhile, making it complicated to inspect their history.

A possible solution may be to make a clone of fty-rest repo (as of Mar 5 2018 or so; maybe using the advanced git commands to cut codebases into submodules etc.), and apply a series of "git mv" and "git rm" commands to rearrange it into current state of fty-common (and then overlay the changes done in fty-common afterwards). If this works well, it will add the searchable history without changing the current codebase state and without requiring an invasive force-push to the fty-common upstream repo.

**Comment by FrancoisRegisDegott-eaton** [comment]
outdated
